In [8]:
import torch
import einops


In [9]:
latent_codes = torch.rand(1,4,10,20)
# B C X Y

In [10]:
latent_codes = torch.rand(1,4,10,20)

# Now, we need to get B 9C X Y by concatenating nearest latent codes
padded_latent_codes = torch.nn.functional.pad(latent_codes, (1,1,1,1))

indices = [(0,-2), (1,-1), (2, None)]
concatenated_latent_codes = torch.cat([padded_latent_codes[..., start_x:stop_x, start_y:stop_y] for start_x, stop_x in indices for start_y, stop_y in indices], dim=1)
print(padded_latent_codes.shape)

torch.Size([1, 4, 12, 22])


In [11]:
indices = [(0,-2), (1,-1), (2, None)]

[print(start_x,stop_x, start_y, stop_y) for start_x, stop_x in indices for start_y, stop_y in indices]

0 -2 0 -2
0 -2 1 -1
0 -2 2 None
1 -1 0 -2
1 -1 1 -1
1 -1 2 None
2 None 0 -2
2 None 1 -1
2 None 2 None


[None, None, None, None, None, None, None, None, None]

In [12]:
concatenated_latent_codes = torch.cat([padded_latent_codes[..., start_x:stop_x, start_y:stop_y] for start_x, stop_x in indices for start_y, stop_y in indices], dim=1)

In [13]:
test = torch.nn.functional.unfold(latent_codes, kernel_size=3, padding=1, stride=1)
test_2d = einops.rearrange(test, "B C (X Y) -> B C X Y", X=10)
test_2d_unfolded = einops.rearrange(test, "B (C nine) (X Y) -> B nine C X Y", nine=9, X=10)
test_2d_rearranged = einops.rearrange(test, "B (C nine) (X Y) -> B (nine C) X Y", nine=9, X=10)

In [35]:
torch.all(test_2d_rearranged == concatenated_latent_codes)

tensor(True)

In [31]:
test_2d_unfolded[0,4,:,0,0]

tensor([0.6268, 0.0577, 0.7081, 0.4242])

In [32]:
test_2d[...,0,0]

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.6268, 0.5980, 0.0000, 0.5939, 0.0602,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0577, 0.5561, 0.0000, 0.2734, 0.9174,
         0.0000, 0.0000, 0.0000, 0.0000, 0.7081, 0.4224, 0.0000, 0.9177, 0.7042,
         0.0000, 0.0000, 0.0000, 0.0000, 0.4242, 0.3268, 0.0000, 0.6078, 0.5160]])

In [80]:
latent_codes[..., 0,1]

tensor([[0.6647, 0.4870, 0.8606, 0.6289]])

In [86]:
concatenated_latent_codes[..., 0, 0]

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3386, 0.5537,
         0.4891, 0.7990, 0.6647, 0.4870, 0.8606, 0.6289, 0.0000, 0.0000, 0.0000,
         0.0000, 0.9919, 0.4100, 0.0449, 0.3308, 0.3333, 0.0579, 0.3864, 0.8924]])

In [50]:
print(concatenated_latent_codes[0, 0:4, 2, 2] == concatenated_latent_codes[0, 16:20, 1, 1])
print(concatenated_latent_codes[0, 16:20, 1, 1] == concatenated_latent_codes[0, 32:36, 0, 0])

tensor([True, True, True, True])
tensor([True, True, True, True])


In [6]:
a = torch.rand(10)
print(einops.repeat(a, "B -> B 1 X Y", X=10, Y=20).shape)

torch.Size([10, 1, 10, 20])
